const mockData = {
  WordPressHosting: [
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
          managed_wordpress: "Free 1-click WordPress installation",
          daily_backups: "Free 1-click Google integration",
          cdn: "Free CDN",
          dedicated_ip: "Free pre-built templates",
          priority_support: "WordPress compatibility checker",
        },
        wordpress: {
          one_click_installation: "WordPress multisite",
          google_integration: "WP-CLI and SSH",
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: "Smart WordPress auto updates",
          vulnerability_scanner: "WordPress acceleration (LiteSpeed)",
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: "AI website builder",
          drag_and_drop_editor: "Drag&Drop editor",
          templates: "150 templates",
          marketing_integrations: "Marketing integrations",
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0% transaction fees",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: "Web application firewall",
          cloudflare_protected_nameservers: "Cloudflare protected nameservers",
          secure_access_manager: "Secure access manager",
        },
        support: {
          bandwidth: "Unlimited bandwidth",
          uptime_guarantee: "99.9% uptime guarantee",
          global_data_centers: "Global Data Centres",
          customer_support: "24/7 customer support",
          money_back_guarantee: "30-Day money-back guarantee",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
          managed_wordpress: "Free 1-click WordPress installation",
          daily_backups: "Free 1-click Google integration",
          cdn: "Free CDN",
          dedicated_ip: "Free pre-built templates",
          priority_support: "WordPress compatibility checker",
        },
        wordpress: {
          one_click_installation: "WordPress multisite",
          google_integration: "WP-CLI and SSH",
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: "Smart WordPress auto updates",
          vulnerability_scanner: "WordPress acceleration (LiteSpeed)",
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: "AI website builder",
          drag_and_drop_editor: "Drag&Drop editor",
          templates: "150 templates",
          marketing_integrations: "Marketing integrations",
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0% transaction fees",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: "Web application firewall",
          cloudflare_protected_nameservers: "Cloudflare protected nameservers",
          secure_access_manager: "Secure access manager",
        },
        support: {
          bandwidth: "Unlimited bandwidth",
          uptime_guarantee: "99.9% uptime guarantee",
          global_data_centers: "Global Data Centres",
          customer_support: "24/7 customer support",
          money_back_guarantee: "30-Day money-back guarantee",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
          managed_wordpress: "Free 1-click WordPress installation",
          daily_backups: "Free 1-click Google integration",
          cdn: "Free CDN",
          dedicated_ip: "Free pre-built templates",
          priority_support: "WordPress compatibility checker",
        },
        wordpress: {
          one_click_installation: "WordPress multisite",
          google_integration: "WP-CLI and SSH",
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: "Smart WordPress auto updates",
          vulnerability_scanner: "WordPress acceleration (LiteSpeed)",
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: "AI website builder",
          drag_and_drop_editor: "Drag&Drop editor",
          templates: "150 templates",
          marketing_integrations: "Marketing integrations",
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0% transaction fees",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: "Web application firewall",
          cloudflare_protected_nameservers: "Cloudflare protected nameservers",
          secure_access_manager: "Secure access manager",
        },
        support: {
          bandwidth: "Unlimited bandwidth",
          uptime_guarantee: "99.9% uptime guarantee",
          global_data_centers: "Global Data Centres",
          customer_support: "24/7 customer support",
          money_back_guarantee: "30-Day money-back guarantee",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
  ],

  LinuxWebHoisting: [
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "linuxExtraDiv",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
  ],

  WindowsHosting: [
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "windowsExtraDiv",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
  ],

  VirtualHosting: [
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "virtualExtraDiv",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
  ],

  BusinessEmail: [
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "businessExtraDiv",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
    {
      name: "Cloud Startup 1",
      clssName: "",
      description: "Optimised performance & guaranteed resources.",
      price: {
        discounted: "699.00",
        original: "1699.00",
        discount: "59% OFF",
        renewal_price: "1279.00",
      },
      additional_offer: "+2 months free",
      anchorLink: "#11",
      features: {
        websites: "111 websites",
        visits: "~10 000 visits monthly",
        storage: "200 GB NVMe storage",
        hosting: {
           managed_wordpress: "hjfjfhfhfhfhf",
          daily_backups: true,
          cdn: "Free CDN",
          dedicated_ip: true,
          priority_support: true,
        },
        wordpress: {
          one_click_installation: true,
          google_integration: true,
          pre_built_templates: true,
          acceleration: "LiteSpeed",
          auto_updates: true,
          vulnerability_scanner: true,
          compatibility_checker: true,
          multisite: true,
          wp_cli_and_ssh: true,
          affiliate_plugin: true,
          staging_tool: true,
          object_cache: true,
          on_demand_backup: true,
          tools: "WordPress AI tools",
        },
        builder: {
          ai_builder: true,
          drag_and_drop_editor: true,
          templates: "150 templates",
          marketing_integrations: true,
          ai_features: [
            "AI image generator",
            "AI writer",
            "AI blog generator",
            "AI heatmaps",
          ],
          seo_tools: true,
          ecommerce_features: true,
          transaction_fees: "0%",
          payment_methods: "20+ payment methods",
        },
        security: {
          ddos_protection: "Enhanced DDoS protection",
          malware_scanner: true,
          domain_privacy: {
            free: true,
            value: "₹749.00",
          },
          web_application_firewall: true,
          cloudflare_protected_nameservers: true,
          secure_access_manager: true,
        },
        support: {
          bandwidth: "Unlimited",
          uptime_guarantee: "99.9%",
          global_data_centers: true,
          customer_support: "24/7",
          money_back_guarantee: "30-Day",
        },
        technical_details: {
          files_and_directories: "2,000,000",
          php_workers: "100",
          visits: "200,000 visits monthly",
          subdomains: "300",
          mysql_connections: "100",
          databases: "800",
          git_access: true,
          multiple_php_versions: true,
          ssh_access: true,
          dns_management: true,
          ftp_accounts: "Unlimited",
          cache_manager: true,
        },
      },
    },
  ],
};

export default mockData;
